name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test # Using any available iPhone simulator
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          xcodebuild -version
          xcodebuild -list -json
          xcrun xctrace list devices
          xcrun --sdk iphonesimulator --show-sdk-path

      - name: Build and test with xcodebuild
        run: |
          # 1. Get the list of available iPhone simulators, and get the first one
          device=`xcrun xctrace list devices | grep -oE 'iPhone.*?[^\(]+' | sed -e "s/ Simulator//" | head -1 | awk '{$1=$1;print}'`

          # 2. Perform the actual build (for testing)
          xcodebuild build-for-testing -scheme "BokenEngine" -destination "platform=iOS Simulator,name=$device"

          # 3. Perform the actual testing using the previous build
          xcodebuild test-without-building -scheme "BokenEngine" -destination "platform=iOS Simulator,name=$device"
